### ISSUE TITLE
http: panic serving pipe: runtime error:

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#17]
The Rancher host ran into memory pressure and had to be rebooted. After reboot, RancherOS2 node onboarding fails and I see the attached log message coming from `ros-operator`:

```
time="2022-02-11T14:52:52Z" level=error msg="error syncing 'default/m-qemu-standard-pc-q35-ich9-2009-not-specified-vbvth': handler machine-inventory: clusters.provisioning.cattle.io \"custom\" not found, requeing" │
│ 2022/02/11 14:53:05 http: panic serving pipe: runtime error: invalid memory address or nil pointer dereference                                                                             │
│ goroutine 974 [running]:                                                                                                                                                                   │
│ net/http.(*conn).serve.func1(0xc0004425a0)                                                                                                                                                 │
│     /usr/lib64/go/1.16/src/net/http/server.go:1824 +0x153                                                                                                                                  │
│ panic(0x1c0bf20, 0x2efb6c0)                                                                                                                                                                │
│     /usr/lib64/go/1.16/src/runtime/panic.go:971 +0x499                                                                                                                                     │
│ github.com/rancher/os2/pkg/server.writeResponse(0x7fd6a83db200, 0xc000623e18, 0xc00000a1e0, 0x0, 0xc000623e18, 0xc000623e48)                                                               │
│     /home/abuild/rpmbuild/BUILD/os2-0.1.0-alpha13/pkg/server/server.go:175 +0xf3                                                                                                           │
│ github.com/rancher/os2/pkg/server.(*InventoryServer).handle(0xc000c4c600, 0x2138860, 0xc000b80a80, 0xc000784b00)                                                                           │
│     /home/abuild/rpmbuild/BUILD/os2-0.1.0-alpha13/pkg/server/server.go:152 +0x42e                                                                                                          │
│ github.com/rancher/os2/pkg/server.(*InventoryServer).ServeHTTP(0xc000c4c600, 0x2138860, 0xc000b80a80, 0xc000784b00)                                                                        │
│     /home/abuild/rpmbuild/BUILD/os2-0.1.0-alpha13/pkg/server/server.go:105 +0xa5                                                                                                           │
│ github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1(0x2138860, 0xc000b80a80, 0xc000784900)                                                                                              │
│     /home/abuild/rpmbuild/BUILD/os2-0.1.0-alpha13/vendor/github.com/rancher/steve/pkg/auth/filter.go:167 +0x1c7                                                                            │
│ net/http.HandlerFunc.ServeHTTP(0xc000ba1500, 0x2138860, 0xc000b80a80, 0xc000784900)                                                                                                        │
│     /usr/lib64/go/1.16/src/net/http/server.go:2069 +0x44                                                                                                                                   │
│ net/http.serverHandler.ServeHTTP(0xc000b80540, 0x2138860, 0xc000b80a80, 0xc000784900)                                                                                                      │
│     /usr/lib64/go/1.16/src/net/http/server.go:2887 +0xa3                                                                                                                                   │
│ net/http.(*conn).serve(0xc0004425a0, 0x213bf40, 0xc000b58c40)                                                                                                                              │
│     /usr/lib64/go/1.16/src/net/http/server.go:1952 +0x8cd                                                                                                                                  │
│ created by net/http.(*Server).Serve                                                                                                                                                        │
│     /usr/lib64/go/1.16/src/net/http/server.go:3013 +0x39b         
```

**Comment by mudler** [comment]
Log seems to be cut on the relevant part, 

```
time="2022-02-11T14:52:52Z" level=error msg="error syncing 'default/m-qemu-standard-pc-q35-ich9-2009-not-specified-vbvth': handler machine-inventory: clusters.provisioning.cattle.io \"cu │
```

Can you attach the full logs? did it crashloopback and started eventually, or it just sit there?

**Comment by kkaempf** [comment]
The message ends with `"custom" not found, requeing`. (I edited the original comment accordingly).

**Comment by kkaempf** [comment]
never happened again
